import roast.*;

// ********** Driver **********

public class Test {

public static void main(String[] args)
{
	try {
		Roast.parseArgs(null,args);
	} catch (ParameterException pe) {
		Roast.logUtilityMessage("Test failed: no exception expected",0);
	}

	int x = 0;
	Roast.logUtilityMessage("Level 0 message: pass",0);
	Roast.logUtilityMessage("Level 1 message: pass",1);
	Roast.logUtilityMessage("Level 2 message: pass",2);
	Roast.logUtilityMessage("Level 3 message: pass",3);
	Roast.logUtilityMessage("Level 4 message: pass",4);
	Roast.logUtilityMessage("Level 5 message: fail",5);
	#valueCheck x # 0 #end
	#excMonitor x = 1; #end

	Roast.printCounts();
}

}
